graph TD;
    spos["Sufficient participants<br/>Organizer set"];
    spno["Sufficient participants<br/>No organizer"];
    mpos["Missing participants<br/>Organizer set"];
    mpno["Missing participants<br/>No organizer"];
    fbno["Fully booked<br/>No organizer"];
    fbos["Fully booked<br/>Organizer set"];
    c["Canceled<br/>Action: Remove all participants<br/>and organizer from event"];
    d["Deleted"];
    i["Init"];

    spos --> |"c2|m2,m3"| spno;
    spos --> |"c4|m2<br/>c9|m2"| mpos;
    spno --> |"c1|m1"| spos;
    mpos --> |"c3|m1<br/>c10|m1"| spos;
    mpos --> |"c2"| mpno;
    mpno --> |"c1"| mpos;
    mpno --> |"c3|m3<br/>c10|m3"| spno;
    spno --> |"c4|m2<br/>c9|m2"| mpno;
    spos --> |"c3|m7<br/>c12|m7"| fbos;
    spno --> |"c3|m7<br/>c12|m7"| fbno;
    fbno --> |"c1|m1"| fbos;
    fbno --> |"c4"| spno;
    fbos --> |"c2|m2,m3"| fbno;
    fbos --> |"c4"| spos;
    fbos --> |"c6|m4"| c;
    fbno --> |"c6|m4"| c;
    spno --> |"c6|m4"| c;
    spno --> |"c3"| spno;
    mpos --> |"c6|m4"| c;
    mpos --> |"c3|m1,m7"| fbos;
    mpno --> |"c3|m1,m3,m7"| fbno;
    mpno --> |"c6|m4"| c;
    spos --> |"c6|m4"| c;
    spos --> |"c3"| spos;
    c --> |"c7|m5"| mpno;
    c --> |"c7|m3,m5"| spno;
    c --> |"c8"| d;
    i --> |"c5|m6"| spos;
    i --> |"c5|m6"| spno;
    i --> |"c5|m6"| mpos;
    i --> |"c5|m6"| mpno;
    i --> |"c5|m3,m6,m7"| fbno;
    i --> |"c5|m6,m7"| fbos;

    condition["Condition\nc1 Organizer set\nc2 Organizer reset\nc3 Participant added\nc4 Participant removed\nc5 New event created\nc6 Event canceled\nc7 Event cancel undone\nc8 Event deleted\nc9 p_min increased to p_min > p\nc10 p_min decreased to p_min ≤ p\nc11 p_max increased to p_max > p\nc12 p_max decreased to p_max ≤ p\n"];
    
    mail["Mail messages\n|m1 'Confirmed open' to all participants and organizer of event\n|m2 'Pending if open' to all participants and organizer of event'\n|m3 'Event with sufficient participants is missing organizer' to all organizers\n|m4 'Canceled' to all participants and organizer of event\n|m5 'Not canceled' to all participants and organizer of event\n|m6 'New event' to all accounts\n|m7 'Fully booked' to all organizers\n"];
    
    participants["Participants p\n|p ≥ 0\n|0 ≤ p_min ≤ p_max\n|Missing participants\n|p < p_min\n|Sufficient participants\n|p ≥ p_min\n|p < p_max\n|Fully booked\n|p ≥ p_max\n"];
